export const SET_LOADING = "SET_LOADING";
export const SEARCH_POKEMONS = "SEARCH_POKEMONS";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const SET_POKEMON_PAGE_SIZE = "SET_POKEMON_PAGE_SIZE";
export const SET_POKEMON_SEARCH_NAME = "SET_POKEMON_SEARCH_NAME";
export const SET_POKEMON_SEARCH_TYPE = "SET_POKEMON_SEARCH_TYPE";
